# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: mkdir staging && mv target/*.jar target/graphql-2-jpa-${{ github.run_number }}.jar && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
        retention-days: 1
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.ACTION_TOKEN }}"
        automatic_release_tag: "${{ github.run_number }}"
        title: "Automated Build ${{ github.run_number }}"
        prerelease: false
        files: staging/*.jar
